index:
    path: /index.html
    controller: App\Controller\DefaultController::index

index2:
    path: /
    controller: App\Controller\DefaultController::index

user_register:
    path: /sign-up.html
    controller: App\Controller\UsersController::index
    
success_register:
    path: /success.html
    controller: App\Controller\UsersController::new