index2:
    path: /index.html
    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\DefaultController::index

user_register:
    path: /sign-up.html
    controller: App\Controller\UsersController::index

success_register:
    path: /success
    controller: App\Controller\SuccessController::index
