index2:
    path: /index.html
    controller: App\Controller\SecurityController::login

index:
    path: /
    controller: App\Controller\SecurityController::login

user_register:
    path: /sign-up.html
    controller: App\Controller\UsersController::index

success_register:
    path: /success
    controller: App\Controller\SuccessController::index

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

users:
    path: /users
    controller: App\Controller\UsersController::show

app_users_edit:
    path: /users/edit/{id}
    controller: App\Controller\UsersController::update
